feat(main): create listMovies feature file
lucasgmelo/cinema-management pull request #3
Opened 2022-07-27 19:56 UTC by IgorEM

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## How to test

Please include instructions about how to test your changes.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

2022-07-28 02:20 UTC, lucasgmelo commented on features/listMovies.feature
> +    I WANT TO list the movies in theaters
Why is this text in uppercase? There's a reason?

2022-07-28 02:22 UTC, lucasgmelo commented on features/listMovies.feature
> +    AS A movie employee
I believe that you should do something like

As a customer
I want to see which movies are available... 

Something like that, because I think this is the customers view, not employee

2022-07-28 02:24 UTC, lucasgmelo commented on features/listMovies.feature
> +        Given the client "Igor Eduardo" is registered and logged in the system
This is actually a question: should the user be logged in the system?
Isn't better that **anyone** can see which movies are available and only in the checkout he needs to log in?

2022-07-28 02:24 UTC, lucasgmelo commented on features/listMovies.feature
> +        And the client "Igor Eduardo" is registered and logged in the system
Same comment about being logged to see movies

2022-07-28 02:26 UTC, lucasgmelo commented on features/listMovies.feature
> +        And "Minions 2" is not shown as a movie poster
I think we should show it as a movie poster, but it should be in a disabled state

2022-07-28 02:27 UTC, lucasgmelo commented on features/listMovies.feature
> +        And "Thor: Love and Thunder" is shown as a movie poster
I don't know if this line is necessary

2022-07-28 02:30 UTC, lucasgmelo commented on features/listMovies.feature
> +         Then "Minions 2" is not shown as a movie poster
Same here, I believe it should be just disabled

2022-07-28 02:36 UTC, lucasgmelo commented on features/listMovies.feature
> +        And the information about the 17:30 session in Room 3 (3D and Subtitled) is omitted
I don't think should be omitted, but should be disabled

2022-07-28 02:37 UTC, lucasgmelo commented on features/listMovies.feature
> +        And the information about the 17:30 session in Room 3 (3D and Subtitled) is omitted
<img width="166" alt="image" src="https://user-images.githubusercontent.com/61155203/181408029-9a567800-42c4-4d0d-b49e-6ff2a425d21c.png">

This symbol means that there is not a line at the end of the file (EOF LINE)
To fix this, you can just add a empty line at the end and it's fixed! :)

2022-07-28 02:38 UTC, lucasgmelo requested changes
Overall, really good PR. Nice job, just pay attention to the comments I've made

2022-07-29 01:58 UTC, IgorEM commented on features/listMovies.feature
> +    I WANT TO list the movies in theaters
done

2022-07-29 01:58 UTC, IgorEM commented on features/listMovies.feature
> +    AS A movie employee
done

2022-07-29 01:58 UTC, IgorEM commented on features/listMovies.feature
> +        Given the client "Igor Eduardo" is registered and logged in the system
done

2022-07-29 01:58 UTC, IgorEM commented on features/listMovies.feature
> +        And the client "Igor Eduardo" is registered and logged in the system
done

2022-07-29 01:58 UTC, IgorEM commented on features/listMovies.feature
> +        And "Minions 2" is not shown as a movie poster
done

2022-07-29 02:00 UTC, IgorEM commented on features/listMovies.feature
> +        And "Thor: Love and Thunder" is shown as a movie poster
which line? this?
And "Thor: Love and Thunder" is shown as a movie poster

2022-07-29 02:00 UTC, IgorEM commented on features/listMovies.feature
> +         Then "Minions 2" is not shown as a movie poster
done

2022-07-29 02:00 UTC, IgorEM commented on features/listMovies.feature
> +        And the information about the 17:30 session in Room 3 (3D and Subtitled) is omitted
done

2022-07-29 02:02 UTC, IgorEM commented on features/listMovies.feature
> +        And the information about the 17:30 session in Room 3 (3D and Subtitled) is omitted
I add an empty line, but the erro continues

2022-07-29 02:17 UTC, closed without merging